name: "Update Terraform Provider Docs"
on:
  pull_request:
    paths:
      - "**/*.go"
      - "templates/**/*"

jobs:
  tfplugindocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: make docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          pull: "--ff"
          message: "Run terragrunt hclfmt"
          add: "docs/**/*.md"
          default_author: github_actions
